id: P005389
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W6489
  title: ཞབས་དཀར་བའི་མགུར་འབུམ
  author: ''
  volumes:
    381e0ffc3e9446dbb0ab29c2a28d3b57:
      image_group_id: I1725
      title: ''
      volume_number: 1
      total_pages: 762
      base_file: v001.txt
